{
  imports = [
    ./nix/apps/distrobox.nix
    ./nix/apps/utils/eza.nix
    ./nix/apps/utils/ripgrep.nix
    ./nix/apps/utils/fd.nix
    ./nix/apps/utils/fzf.nix
    ./nix/apps/sudo.nix
    ./nix/apps/containers/podman.nix
    ./nix/apps/fonts.nix
    ./nix/apps/nix-index.nix
    ./nix/apps/gh.nix
    ./nix/apps/shells/tmux.nix
    ./nix/apps/shells/nzf.nix
    ./nix/apps/editors/nvf.nix
    ./nix/apps/git.nix
    ./nix/apps/development/direnv.nix
    ./nix/apps/development/devbox.nix
    ./nix/hosts/blackout/default.nix
    ./nix/defaultTags.nix
  ];
}
